# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Syndesis"
license = "MIT"
licenselink = "https://github.com/syndesisio/syndesis/blob/master/LICENSE.md"
description = "A flexible, customizable, open source platform that provides core integration capabilities as a service."
homepage = "http://www.syndesis.io/"
tags = []
features = []
min_version = "0.20.6"

[author]
  name = "Red Hat, Inc."
  homepage = "http://www.redhat.com/"
