baseURL = "https://syndesis.io/"
languageCode = "en-gb"
enableGitInfo = true
title = "Syndesis"
theme = "syndesis"
relativeURLs = true
googleAnalytics = "UA-98663114-1"
description = "A flexible, customizable, open source platform that provides core integration capabilities as a service."

Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "Red Hat"
  github = "syndesisio" # add your github profile name
  twitter = "syndesisio" # add your twitter profile
  email = "syndesis-admin@googlegroups.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
